server:
  port: 9010

spring:
  #main:
   # lazy-initialization: true
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orbita_pragma
    username: desarrollo
    password: desarrollo1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: usuarios

management:
  endpoints:
    web:
      exposure:
        include: "*"